### ISSUE TITLE
Error: Failed to lookup view "index" in views directory

### ISSUE THREAD

**Issue by AhmadMWaddah** [AhmadMWaddah/AMWStore#1]
i don't know when i open my app and it works without any error on terminal but when i try to open file from browser it pop up this errors in terminal and in browser body.

Terminal Error:

**Server Started on Port 3000
Connected To DB.
Error: Failed to lookup view "index" in views directory "/home/ahmdmwddh/ZBusinessCrt/WebDev/JsCrt/AMWStore/views"
    at Function.render (/home/ahmdmwddh/ZBusinessCrt/WebDev/JsCrt/AMWStore/node_modules/express/lib/application.js:580:17)
    at ServerResponse.render (/home/ahmdmwddh/ZBusinessCrt/WebDev/JsCrt/AMWStore/node_modules/express/lib/response.js:1012:7)
    at /home/ahmdmwddh/ZBusinessCrt/WebDev/JsCrt/AMWStore/app.js:29:8
    at Layer.handle [as handle_request] (/home/ahmdmwddh/ZBusinessCrt/WebDev/JsCrt/AMWStore/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/ahmdmwddh/ZBusinessCrt/WebDev/JsCrt/AMWStore/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/ahmdmwddh/ZBusinessCrt/WebDev/JsCrt/AMWStore/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/ahmdmwddh/ZBusinessCrt/WebDev/JsCrt/AMWStore/node_modules/express/lib/router/layer.js:95:5)
    at /home/ahmdmwddh/ZBusinessCrt/WebDev/JsCrt/AMWStore/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/ahmdmwddh/ZBusinessCrt/WebDev/JsCrt/AMWStore/node_modules/express/lib/router/index.js:335:12)
    at next (/home/ahmdmwddh/ZBusinessCrt/WebDev/JsCrt/AMWStore/node_modules/express/lib/router/index.js:275:10)
    at SendStream.error (/home/ahmdmwddh/ZBusinessCrt/WebDev/JsCrt/AMWStore/node_modules/serve-static/index.js:121:7)
    at SendStream.emit (events.js:314:20)
    at SendStream.error (/home/ahmdmwddh/ZBusinessCrt/WebDev/JsCrt/AMWStore/node_modules/send/index.js:270:17)
    at SendStream.onStatError (/home/ahmdmwddh/ZBusinessCrt/WebDev/JsCrt/AMWStore/node_modules/send/index.js:421:12)
    at next (/home/ahmdmwddh/ZBusinessCrt/WebDev/JsCrt/AMWStore/node_modules/send/index.js:763:28)
    at /home/ahmdmwddh/ZBusinessCrt/WebDev/JsCrt/AMWStore/node_modules/send/index.js:771:23**

**Comment by AhmadMWaddah** [comment]
Solved:
Problem Was With Path Its Not Correct Using Console log Saw it and Changed To Correct Path.
